apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db-deployment
  labels:
    app: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres-db
        image: nenonesa/postgres:latest
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: mysecretpassword
          - name: POSTGRES_DB
            value: mydatabase