apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: postgres-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nenonesa/webapp-backend:latest
        ports:
          - containerPort: 5050