name: Webapp CI/CD workflow

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    name: Build Frontend
    steps:
      - name: Test Step
        run: echo "Test step"
  build-backend:
    name: Build Backend
    steps:
      - name: Test Step
        run: echo "Test step"
  deploy-prd:
    name: Deploy to PROD (K8S)
    steps:
      - name: Test Step
        run: echo "Test step"
  api-tests-prd:
    name: API Tests on PROD
    steps:
      - name: Test Step
        run: echo "Test step"
  rollback-backend:
    name: Backend rollback on PROD
    steps:
      - name: Test Step
        run: echo "Test step"

