name: Webapp CI/CD workflow

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Path filter
        uses: dorny/paths-filter@v3
        id: filters
        with:
          filters: |
            frontend:
              - 'frontend/**'
      - name: Build Frontend application
        if: steps.filters.outputs.frontend == 'true'
        uses: ./.github/actions/build
        with:
          image_tag: ${{ secrets.DOCKERHUB_USERNAME }}/webapp-frontend:$GITHUB_SHA
          application: frontend
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
  build-backend:
    name: Build Backend
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Path filter
        uses: dorny/paths-filter@v3
        id: filters
        with:
          filters: |
            backend:
              - 'backend/**'
      - name: Build Backend application
        if: steps.filters.outputs.backend == 'true'
        uses: ./.github/actions/build
        with:
          image_tag: ${{ secrets.DOCKERHUB_USERNAME }}/webapp-backend:$GITHUB_SHA
          application: backend
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
  deploy-prod:
    name: Deploy to PROD (K8S)
    runs-on: self-hosted
    needs: [build-frontend, build-backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Path filter
        uses: dorny/paths-filter@v3
        id: filters
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'
      - name: Deploy Frontend to PROD
        uses: ./github/actions/deploy
        with:
          image_tag: ${{ secrets.DOCKERHUB_USERNAME }} /webapp-frontend:$GITHUB_SHA
          deployment_name: frontend-deployment
          container_name: frontend   
      - name: Deploy Backend to PROD
        uses: ./github/actions/deploy
        with:
          image_tag: ${{ secrets.DOCKERHUB_USERNAME }} /webapp-backend:$GITHUB_SHA
          deployment_name: backend-deployment
          container_name: backend       
      

  api-tests-prod:
    name: API Tests on PROD
    runs-on: self-hosted
    needs: [deploy-prod]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Path filter
        uses: dorny/paths-filter@v3
        id: filters
        with:
          filters: |
            backend:
              - 'backend/**'
      - name: Run API tests on PROD
        if: steps.filters.outputs.backend == 'true'
        run: |
          docker pull nenonesa/api-tests:latest
          docker run --rm --network=host --name api-tests-prod nenonesa/api-tests:latest cucumber PLATFORM=PRD

  rollback-backend:
    name: Backend rollback on PROD
    needs: [api-tests-prod]
    runs-on: self-hosted
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - name: Rollback for the Backend (PROD)
        run: |
          kubectl rollout undo deployments backend-deployment

