name: Webapp CI/CD workflow

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Path filter
        uses: dorny/paths-filter@v3
        id: filters
        with:
          filters: |
            frontend:
              - 'frontend/**'
      - name: Docker login
        if: steps.filters.outputs.frontend == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          logout: false
      - name: Build and Push docker image
        if: steps.filters.outputs.frontend == 'true'
        run: |
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/webapp-frontend:$GITHUB_SHA ./frontend
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/webapp-frontend:$GITHUB_SHA
  build-backend:
    name: Build Backend
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Path filter
        uses: dorny/paths-filter@v3
        id: filters
        with:
          filters: |
            backend:
              - 'backend/**'
      - name: Docker login
        if: steps.filters.outputs.backend == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          logout: false
      - name: Build and Push docker image
        if: steps.filters.outputs.backend == 'true'
        run: |
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/webapp-backend:$GITHUB_SHA ./backend
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/webapp-backend:$GITHUB_SHA
      
  deploy-prod:
    name: Deploy to PROD (K8S)
    runs-on: self-hosted
    needs: [build-frontend, build-backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Path filter
        uses: dorny/paths-filter@v3
        id: filters
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'
      - name: Deploy Frontend to PROD
        if: steps.filters.outputs.frontend == 'true'
        run: |
          kubectl set image deployment/frontend-deployment frontend=nenonesa/webapp-frontend:$GITHUB_SHA
      - name: Deploy Backend to PROD
        if: steps.filters.outputs.backend == 'true'
        run: |
          kubectl set image deployment/backend-deployment backend=nenonesa/webapp-backend:$GITHUB_SHA

  api-tests-prod:
    name: API Tests on PROD
    runs-on: self-hosted
    needs: [deploy-prod]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Path filter
        uses: dorny/paths-filter@v3
        id: filters
        with:
          filters: |
            backend:
              - 'backend/**'
      - name: Run API tests on PROD
        if: steps.filters.outputs.backend == 'true'
        run: |
          docker pull nenonesa/api-tests:latest
          docker run --rm --network=host --name api-tests-prod nenonesa/api-tests:latest cucumber PLATFORM=PRD

  rollback-backend:
    name: Backend rollback on PROD
    needs: [api-tests-prod]
    runs-on: self-hosted
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - name: Rollback for the Backend (PROD)
        run: |
          kubectl rollout undo deployments backend-deployment

