name: Webapp CI/CD workflow

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          logout: false
      - name: Build and Push docker image
        run: |
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/webapp-frontend:latest ./frontend
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/webapp-frontend:latest
  build-backend:
    name: Build Backend
    runs-on: self-hosted
    steps:
      - name: Test Step
        run: echo "Test step"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          logout: false
      - name: Build and Push docker image
        run: |
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/webapp-backend:latest ./backend
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/webapp-backend:latest
      
  deploy-prod:
    name: Deploy to PROD (K8S)
    runs-on: self-hosted
    needs: [build-frontend, build-backend]
    steps:
      - name: Deploy Frontend to PROD
        run: |
          kubectl set image deployment/frontend-deployment frontend=nenonesa/webapp-frontend:latest
          kubectl rollout restart deployment/frontend-deployment
      - name: Deploy Backend to PROD
        run: |
          kubectl set image deployment/backend-deployment backend=nenonesa/webapp-backend:latest
          kubectl rollout restart deployment/backend-deployment

  api-tests-prod:
    name: API Tests on PROD
    runs-on: self-hosted
    needs: [deploy-prod]
    steps:
      - name: Run API tests on PROD
        run: |
          docker pull nenonesa/api-tests:latest
          docker run --rm --network=host --name api-tests-prod nenonesa/api-tests:latest cucumber PLATFORM=PRD
  rollback-backend:
    name: Backend rollback on PROD
    needs: [api-tests-prod]
    runs-on: self-hosted
    steps:
      - name: Rollback for the Backend (PROD)
        run: |
          kubectl rollout undo deployments backend-deployment

